version: 2

# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
updates:
  # https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: github-actions
    assignees:
      - creatch
    commit-message:
      prefix: deps
    directory: /
    labels:
      - bot
      - bot-dependabot
      - github-actions
    open-pull-requests-limit: 25
    schedule:
      interval: daily
      time: '11:00'
      timezone: Etc/UTC
